packageExtensions:
  "@vue/test-utils@2.*":
    dependencies:
      "@vue/compiler-dom": "*"
  eslint@^8.0.0:
    dependencies:
      "@eslint/eslintrc": ^1.3.3

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-licenses.cjs
    spec: "https://raw.githubusercontent.com/mhassan1/yarn-plugin-licenses/v0.8.1/bundles/@yarnpkg/plugin-licenses.js"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

supportedArchitectures:
  os:
    - current
    - linux
    - win32
    - linux-arm64

yarnPath: .yarn/releases/yarn-3.6.1.cjs
